<?php

namespace SynerBay\Helper;

use SynerBay\Repository\CurrencyRepository;
use SynerBay\Repository\VendorRepository;
use SynerBay\Resource\CurrencyResource;
use WP_Term;

class SynerBayDataHelper
{
    public static function getMaterialTypes(): array
    {
        return ArrayHelper::reKeyBySlugFromValue([
            '-',
            'Wood',
            'Metal',
            'Plastic',
            'Textil',
            'Latex',
            'PVC',
            'Silicone',
            'Leather',
            'Paper',
            'Fiber',
            'Glass',
            'Chemical',
            'Composite-material',
            'Mineral',
            'Stone',
            'Concrete',
            'Plaster',
            'Ceramic',
            'Rubber',
            'Foam',
            'Semiconductor',
            'Rare-earths',
            'Other',
        ]);
    }

    public static function getUnitTypes(): array
    {
        return ArrayHelper::reKeyBySlugFromValue([
            'piece',
            'mm',
            'cm',
            'm',
            'km',
            'ft',
            'in',
            'mg',
            'g',
            'dg',
            'kg',
            'ml',
            'cl',
            'dl',
            'l',
            'mm2',
            'cm2',
            'm2',
            'km2',
            'other',
        ]);
    }

    public static function getOfferTransportParityTypes(): array
    {
        return [
            'exw' => 'EXW – Ex Works (named place of delivery)',
            'fca' => 'FCA – Free Carrier (named place of delivery)',
            'cpt' => 'CPT – Carriage Paid To (named place of destination)',
            'cip' => 'CIP – Carriage and Insurance Paid to (named place of destination)',
            'dpu' => 'DPU – Delivered At Place Unloaded (named place of destination)',
            'dap' => 'DAP – Delivered At Place (named place of destination)',
            'ddp' => 'DDP – Delivered Duty Paid (named place of destination)',
            'fas' => 'FAS – Free Alongside Ship (named port of shipment)',
            'fob' => 'FOB – Free on Board (named port of shipment)',
            'cfr' => 'CFR – Cost and Freight (named port of destination)',
            'cif' => 'CIF – Cost, Insurance & Freight (named port of destination)',
            'daf' => 'DAF – Delivered at Frontier (named place of delivery)',
            'dat' => 'DAT – Delivered at Terminal',
            'des' => 'DES – Delivered Ex Ship',
            'deq' => 'DEQ – Delivered Ex Quay (named port of delivery)',
            'ddu' => 'DDU – Delivered Duty Unpaid (named place of destination)',
        ];
    }

    public static function setupDeliveryDestinationsForOfferData(array $deliveryDestinationsSlugs): array
    {
        $ret = [];
        $destinations = self::getDeliveryDestinationsForOfferWithCountries();

        foreach ($deliveryDestinationsSlugs as $slug) {
            if (array_key_exists($slug, $destinations)) {
                $ret[] = $destinations[$slug];
            }
        }

        return $ret;
    }

    public static function getDeliveryDestinationsForOffer(): array
    {
        return ArrayHelper::reKeyBySlugFromValue([
            'Worldwide',
            'Africa',
            'North America',
            'South America',
            'Europe',
            'Asia',
            'Middle East',
            'Ocean Pacific',
        ]);
    }

    public static function getDeliveryDestinationsForOfferWithCountries(): array
    {
        return ArrayHelper::reKeyBySlugFromValue(array_values(self::getDeliveryDestinationsList()));
    }

    public static function getYesNo(): array
    {
        return ArrayHelper::reKeyBySlugFromValue([
            'Yes',
            'No',
        ]);
    }

    // a child/functions.php-ban van hgsználva és a merge elhalt sokszor
    public static function getDeliveryDestinations(): array
    {
        return ['' => __('Select shipping to')] + self::getDeliveryDestinationsList();
    }

    public static function getDeliveryDestinationsList(): array
    {
        return [
            'Worldwide' => 'Worldwide',
            'Africa' => 'Africa',
            'North America' => 'North America',
            'South America' => 'South America',
            'Europe' => 'Europe',
            'Asia' => 'Asia',
            'Middle East' => 'Middle East',
            'Ocean Pacific' => 'Ocean Pacific',
            'AF' => 'Afghanistan',
            'AX' => 'Aland Islands',
            'AL' => 'Albania',
            'DZ' => 'Algeria',
            'AS' => 'American Samoa',
            'AD' => 'Andorra',
            'AO' => 'Angola',
            'AI' => 'Anguilla',
            'AQ' => 'Antarctica',
            'AG' => 'Antigua And Barbuda',
            'AR' => 'Argentina',
            'AM' => 'Armenia',
            'AW' => 'Aruba',
            'AU' => 'Australia',
            'AT' => 'Austria',
            'AZ' => 'Azerbaijan',
            'BS' => 'Bahamas',
            'BH' => 'Bahrain',
            'BD' => 'Bangladesh',
            'BB' => 'Barbados',
            'BY' => 'Belarus',
            'BE' => 'Belgium',
            'BZ' => 'Belize',
            'BJ' => 'Benin',
            'BM' => 'Bermuda',
            'BT' => 'Bhutan',
            'BO' => 'Bolivia',
            'BA' => 'Bosnia And Herzegovina',
            'BW' => 'Botswana',
            'BV' => 'Bouvet Island',
            'BR' => 'Brazil',
            'IO' => 'British Indian Ocean Territory',
            'BN' => 'Brunei Darussalam',
            'BG' => 'Bulgaria',
            'BF' => 'Burkina Faso',
            'BI' => 'Burundi',
            'KH' => 'Cambodia',
            'CM' => 'Cameroon',
            'CA' => 'Canada',
            'CV' => 'Cape Verde',
            'KY' => 'Cayman Islands',
            'CF' => 'Central African Republic',
            'TD' => 'Chad',
            'CL' => 'Chile',
            'CN' => 'China',
            'CX' => 'Christmas Island',
            'CC' => 'Cocos (Keeling) Islands',
            'CO' => 'Colombia',
            'KM' => 'Comoros',
            'CG' => 'Congo',
            'CD' => 'Congo, Democratic Republic',
            'CK' => 'Cook Islands',
            'CR' => 'Costa Rica',
            'CI' => 'Cote D\'Ivoire',
            'HR' => 'Croatia',
            'CU' => 'Cuba',
            'CY' => 'Cyprus',
            'CZ' => 'Czech Republic',
            'DK' => 'Denmark',
            'DJ' => 'Djibouti',
            'DM' => 'Dominica',
            'DO' => 'Dominican Republic',
            'EC' => 'Ecuador',
            'EG' => 'Egypt',
            'SV' => 'El Salvador',
            'GQ' => 'Equatorial Guinea',
            'ER' => 'Eritrea',
            'EE' => 'Estonia',
            'ET' => 'Ethiopia',
            'FK' => 'Falkland Islands (Malvinas)',
            'FO' => 'Faroe Islands',
            'FJ' => 'Fiji',
            'FI' => 'Finland',
            'FR' => 'France',
            'GF' => 'French Guiana',
            'PF' => 'French Polynesia',
            'TF' => 'French Southern Territories',
            'GA' => 'Gabon',
            'GM' => 'Gambia',
            'GE' => 'Georgia',
            'DE' => 'Germany',
            'GH' => 'Ghana',
            'GI' => 'Gibraltar',
            'GR' => 'Greece',
            'GL' => 'Greenland',
            'GD' => 'Grenada',
            'GP' => 'Guadeloupe',
            'GU' => 'Guam',
            'GT' => 'Guatemala',
            'GG' => 'Guernsey',
            'GN' => 'Guinea',
            'GW' => 'Guinea-Bissau',
            'GY' => 'Guyana',
            'HT' => 'Haiti',
            'HM' => 'Heard Island & Mcdonald Islands',
            'VA' => 'Holy See (Vatican City State)',
            'HN' => 'Honduras',
            'HK' => 'Hong Kong',
            'HU' => 'Hungary',
            'IS' => 'Iceland',
            'IN' => 'India',
            'ID' => 'Indonesia',
            'IR' => 'Iran, Islamic Republic Of',
            'IQ' => 'Iraq',
            'IE' => 'Ireland',
            'IM' => 'Isle Of Man',
            'IL' => 'Israel',
            'IT' => 'Italy',
            'JM' => 'Jamaica',
            'JP' => 'Japan',
            'JE' => 'Jersey',
            'JO' => 'Jordan',
            'KZ' => 'Kazakhstan',
            'KE' => 'Kenya',
            'KI' => 'Kiribati',
            'KR' => 'Korea',
            'KW' => 'Kuwait',
            'KG' => 'Kyrgyzstan',
            'LA' => 'Lao People\'s Democratic Republic',
            'LV' => 'Latvia',
            'LB' => 'Lebanon',
            'LS' => 'Lesotho',
            'LR' => 'Liberia',
            'LY' => 'Libyan Arab Jamahiriya',
            'LI' => 'Liechtenstein',
            'LT' => 'Lithuania',
            'LU' => 'Luxembourg',
            'MO' => 'Macao',
            'MK' => 'Macedonia',
            'MG' => 'Madagascar',
            'MW' => 'Malawi',
            'MY' => 'Malaysia',
            'MV' => 'Maldives',
            'ML' => 'Mali',
            'MT' => 'Malta',
            'MH' => 'Marshall Islands',
            'MQ' => 'Martinique',
            'MR' => 'Mauritania',
            'MU' => 'Mauritius',
            'YT' => 'Mayotte',
            'MX' => 'Mexico',
            'FM' => 'Micronesia, Federated States Of',
            'MD' => 'Moldova',
            'MC' => 'Monaco',
            'MN' => 'Mongolia',
            'ME' => 'Montenegro',
            'MS' => 'Montserrat',
            'MA' => 'Morocco',
            'MZ' => 'Mozambique',
            'MM' => 'Myanmar',
            'NA' => 'Namibia',
            'NR' => 'Nauru',
            'NP' => 'Nepal',
            'NL' => 'Netherlands',
            'AN' => 'Netherlands Antilles',
            'NC' => 'New Caledonia',
            'NZ' => 'New Zealand',
            'NI' => 'Nicaragua',
            'NE' => 'Niger',
            'NG' => 'Nigeria',
            'NU' => 'Niue',
            'NF' => 'Norfolk Island',
            'MP' => 'Northern Mariana Islands',
            'NO' => 'Norway',
            'OM' => 'Oman',
            'PK' => 'Pakistan',
            'PW' => 'Palau',
            'PS' => 'Palestinian Territory, Occupied',
            'PA' => 'Panama',
            'PG' => 'Papua New Guinea',
            'PY' => 'Paraguay',
            'PE' => 'Peru',
            'PH' => 'Philippines',
            'PN' => 'Pitcairn',
            'PL' => 'Poland',
            'PT' => 'Portugal',
            'PR' => 'Puerto Rico',
            'QA' => 'Qatar',
            'RE' => 'Reunion',
            'RO' => 'Romania',
            'RU' => 'Russian Federation',
            'RW' => 'Rwanda',
            'BL' => 'Saint Barthelemy',
            'SH' => 'Saint Helena',
            'KN' => 'Saint Kitts And Nevis',
            'LC' => 'Saint Lucia',
            'MF' => 'Saint Martin',
            'PM' => 'Saint Pierre And Miquelon',
            'VC' => 'Saint Vincent And Grenadines',
            'WS' => 'Samoa',
            'SM' => 'San Marino',
            'ST' => 'Sao Tome And Principe',
            'SA' => 'Saudi Arabia',
            'SN' => 'Senegal',
            'RS' => 'Serbia',
            'SC' => 'Seychelles',
            'SL' => 'Sierra Leone',
            'SG' => 'Singapore',
            'SK' => 'Slovakia',
            'SI' => 'Slovenia',
            'SB' => 'Solomon Islands',
            'SO' => 'Somalia',
            'ZA' => 'South Africa',
            'GS' => 'South Georgia And Sandwich Isl.',
            'ES' => 'Spain',
            'LK' => 'Sri Lanka',
            'SD' => 'Sudan',
            'SR' => 'Suriname',
            'SJ' => 'Svalbard And Jan Mayen',
            'SZ' => 'Swaziland',
            'SE' => 'Sweden',
            'CH' => 'Switzerland',
            'SY' => 'Syrian Arab Republic',
            'TW' => 'Taiwan',
            'TJ' => 'Tajikistan',
            'TZ' => 'Tanzania',
            'TH' => 'Thailand',
            'TL' => 'Timor-Leste',
            'TG' => 'Togo',
            'TK' => 'Tokelau',
            'TO' => 'Tonga',
            'TT' => 'Trinidad And Tobago',
            'TN' => 'Tunisia',
            'TR' => 'Turkey',
            'TM' => 'Turkmenistan',
            'TC' => 'Turks And Caicos Islands',
            'TV' => 'Tuvalu',
            'UG' => 'Uganda',
            'UA' => 'Ukraine',
            'AE' => 'United Arab Emirates',
            'GB' => 'United Kingdom',
            'US' => 'United States',
            'UM' => 'United States Outlying Islands',
            'UY' => 'Uruguay',
            'UZ' => 'Uzbekistan',
            'VU' => 'Vanuatu',
            'VE' => 'Venezuela',
            'VN' => 'Viet Nam',
            'VG' => 'Virgin Islands, British',
            'VI' => 'Virgin Islands, U.S.',
            'WF' => 'Wallis And Futuna',
            'EH' => 'Western Sahara',
            'YE' => 'Yemen',
            'ZM' => 'Zambia',
            'ZW' => 'Zimbabwe',
        ];
    }

    public static function getCategories(): array
    {
        return [
            'Agriculture & Food' => [
                'Agriculture' => [
                    'Agricultural Waste',
                    'Animal Products',
                    'Beans',
                    'Cocoa Beans',
                    'Coffee Beans',
                    'Farm Machinery & Equipment',
                    'Feed',
                    'Fresh Seafood',
                    'Fruit',
                    'Grain',
                    'Herbal Cigars & Cigarettes',
                    'Mushrooms & Truffles',
                    'Nuts & Kernels',
                    'Ornamental Plants',
                    'Other Agriculture Products',
                    'Plant & Animal Oil',
                    'Plant Seeds & Bulbs',
                    'Timber Raw Materials',
                    'Vanilla Beans',
                    'Vegetables',
                ],
                'Food & Beverage' => [
                    'Alcoholic Beverage',
                    'Baby Food',
                    'Baked Goods',
                    'Bean Products',
                    'Canned Food',
                    'Coffee',
                    'Confectionery',
                    'Dairy',
                    'Drinking Water',
                    'Egg & Egg Products',
                    'Food Ingredients',
                    'Fruit Products',
                    'Grain Products',
                    'Honey Products',
                    'Instant Food',
                    'Meat & Poultry',
                    'Other Food & Beverage',
                    'Seafood',
                    'Seasonings & Condiments',
                    'Snack Food',
                    'Soft Drinks',
                    'Tea',
                    'Vegetable Products',
                ],
            ],
            'Apparel,Textiles & Accessories' => [
                'Apparel' => [
                    'Apparel Design Services',
                    'Apparel Processing Services',
                    'Apparel Stock',
                    'Boy\'s Clothing',
                    'Costumes',
                    'Ethnic Clothing',
                    'Garment Accessories',
                    'Girl‘s Clothing',
                    'Infant & Toddlers Clothing',
                    'Mannequins',
                    'Maternity Clothing',
                    'Men‘s Clothing',
                    'Sewing Supplies',
                    'Sportswear',
                    'Stage & Dance Wear',
                    'Tag Guns',
                    'Uniforms',
                    'Used Clothes',
                    'Wedding Apparel & Accessories',
                    'Women\'s Clothing',
                ],
                'Textile & Leather Product' => [
                    'Down & Feather',
                    'Fabric',
                    'Fiber',
                    'Fur',
                    'Grey Fabric',
                    'Home Textile',
                    'Leather',
                    'Leather Product',
                    'Other Textiles & Leather Products',
                    'Textile Accessories',
                    'Textile Processing',
                    'Thread',
                    'Yarn',
                    '100% Cotton Fabric',
                    '100% Polyester Fabric',
                    'Bedding Set',
                    'Towel',
                    'Chair Cover',
                    'Genuine Leather',
                ],
                'Fashion Accessories' => [
                    'Belt Accessories',
                    'Belts',
                    'Fashion Accessories Design Services',
                    'Fashion Accessories Processing Services',
                    'Gloves & Mittens',
                    'Scarf, Hat & Glove Sets',
                    'Hats & Caps',
                    'Scarves & Shawls',
                    'Hair Accessories',
                    'Genuine Leather Belts',
                    'Leather Gloves & Mittens',
                    'Ties & Accessories',
                    'Belt Buckles',
                    'PU Belts',
                    'Belt Chains',
                    'Metal Belts',
                    'Suspenders',
                ],
                'Timepieces, Jewelry, Eyewear' => [
                    'Eyewear',
                    'Jewelry',
                    'Watches',
                    'Eyeglasses Frames',
                    'Sunglasses',
                    'Sports Eyewear',
                    'Body Jewelry',
                    'Bracelets & Bangles',
                    'Brooches',
                    'Cuff Links & Tie Clips',
                    'Earrings',
                    'Jewelry Boxes',
                    'Jewelry Sets',
                    'Jewelry Tools & Equipment',
                    'Loose Beads',
                    'Loose Gemstone',
                    'Necklaces',
                    'Pendants & Charms',
                    'Rings',
                    'Wristwatches',
                ],
            ],
            'Auto & Transportation' => [
                'Vehicles & Accessories' => [
                    'Automobiles',
                    'Trailers',
                    'Trucks',
                    'Golf Carts',
                    'Marine Parts & Accessories',
                    'Truck Parts & Accessories',
                    'Trains',
                    'Motorcycles & Scooters',
                    'Auto Parts & Accessories',
                    'Emergency Vehicles',
                    'Bus Parts & Accessories',
                    'ATVs & UTVs',
                    'Bus',
                    'Containers',
                    'Other Vehicle Parts & Accessories',
                    'Other Vehicles',
                ],
            ],
            'Bags, Shoes & Accessories' => [
                'Luggage, Bags & Cases' => [
                    'Bag & Luggage Making Materials',
                    'Bag Parts & Accessories',
                    'Business Bags & Cases',
                    'Digital Gear & Camera Bags',
                    'Handbags & Messenger Bags',
                    'Luggage & Travel Bags',
                    'Luggage Cart',
                    'Other Luggage, Bags & Cases',
                    'Special Purpose Bags & Cases',
                    'Sports & Leisure Bags',
                    'Wallets & Holders',
                    'Carry-on Luggage',
                    'Luggage Sets',
                    'Trolley Bags',
                    'Briefcases',
                    'Cosmetic Bags & Cases',
                    'Shopping Bags',
                    'Handbags',
                    'Backpacks',
                    'Wallets',
                ],
                'Shoes & Accessories' => [
                    'Baby Shoes',
                    'Children\'s Shoes',
                    'Dance Shoes',
                    'Genuine Leather Shoes',
                    'Men\'s Shoes',
                    'Other Shoes',
                    'Shoe Materials',
                    'Shoe Parts & Accessories',
                    'Shoe Repairing Equipment',
                    'Shoes Design Services',
                    'Shoes Processing Services',
                    'Shoes Stock',
                    'Special Purpose Shoes',
                    'Sports Shoes',
                    'Used Shoes',
                    'Women\'s Shoes',
                ],
            ],
            'Electronics' => [
                'Consumer Electronic' => [
                    'Computer Hardware & Software',
                    'Electronic Cigarettes',
                    'Accessories & Parts',
                    'Camera, Photo & Accessories',
                    'Electronic Publications',
                    'Home Audio, Video & Accessories',
                    'Mobile Phone & Accessories',
                    'Other Consumer Electronics',
                    'Portable Audio, Video & Accessories',
                    'Video Game & Accessories',
                    'Mobile Phones',
                    'Earphone & Headphone',
                    'Power Banks',
                    'Digital Camera',
                    'Radio & TV Accessories',
                    'Speaker',
                    'Television',
                    'Cables',
                    'Charger',
                    'Digital Battery',
                    'Digital Photo Frame',
                    '3D Glasses',
                ],
                'Home Appliance' => [
                    'Air Conditioning Appliances',
                    'Cleaning Appliances',
                    'Hand Dryers',
                    'Home Appliance Parts',
                    'Home Appliances Stocks',
                    'Home Heaters',
                    'Kitchen Appliances',
                    'Laundry Appliances',
                    'Other Home Appliances',
                    'Refrigerators & Freezers',
                    'Water Heaters',
                    'Water Treatment Appliances',
                    'Wet Towel Dispensers',
                    'Air Conditioners',
                    'Fans',
                    'Vacuum Cleaners',
                    'Solar Water Heaters',
                    'Cooking Appliances',
                    'Coffee Makers',
                    'Blenders',
                ],
                'Security & Protection' => [
                    'Locks & Keys',
                    'Personal Protective Equipment',
                    'Access Control Systems & Products',
                    'Alarm',
                    'CCTV Products',
                    'Firefighting Supplies',
                    'Locksmith Supplies',
                    'Other Security & Protection Products',
                    'Police & Military Supplies',
                    'Roadway Safety',
                    'Safes',
                    'Security Services',
                    'Self Defense Supplies',
                    'Water Safety Products',
                    'CCTV Camera',
                    'Bullet Proof Vest',
                    'Alcohol Tester',
                    'Fire Alarm',
                ],
            ],
            'Electrical Equipment, Components & Telecoms' => [
                'Electrical Equipment & Supplies' => [
                    'Solar Energy Products',
                    'Batteries',
                    'Electrical Instruments',
                    'Circuit Breakers',
                    'Connectors & Terminals',
                    'Industrial Controls',
                    'Contactors',
                    'Motors',
                    'Electrical Supplies',
                    'Electronic & Instrument Enclosures',
                    'Fuse Components',
                    'Fuses',
                    'Generators',
                    'Power Accessories',
                    'Power Distribution Equipment',
                    'Power Supplies',
                    'Professional Audio, Video & Lighting',
                    'Relays',
                    'Switches',
                    'Transformers',
                    'Wires, Cables & Cable Assemblies',
                    'Wiring Accessories',
                    'Solar Cells, Solar Panel',
                ],
            ],
            'Gifts, Sports & Toys' => [
                'Sports & Entertainment' => [
                    'Amusement Park',
                    'Artificial Grass & Sports Flooring',
                    'Fitness & Body Building',
                    'Gambling',
                    'Golf',
                    'Indoor Sports',
                    'Musical Instruments',
                    'Other Sports & Entertainment Products',
                    'Outdoor Sports',
                    'Sports Gloves',
                    'Sports Safety',
                    'Sports Souvenirs',
                    'Team Sports',
                    'Tennis',
                    'Water Sports',
                    'Winter Sports',
                    'Camping & Hiking',
                    'Scooters',
                    'Gym Equipment',
                    'Swimming & Diving',
                ],
                'Gifts & Crafts' => [
                    'Art & Collectible',
                    'Crafts',
                    'Arts & Crafts Stocks',
                    'Cross Stitch',
                    'Festive & Party Supplies',
                    'Flags, Banners & Accessories',
                    'Gift Sets',
                    'Holiday Gifts',
                    'Home Decoration',
                    'Key Chains',
                    'Knitting & Crocheting',
                    'Lacquerware',
                    'Lanyard',
                    'Money Boxes',
                    'Music Boxes',
                    'Pottery & Enamel',
                    'Sculptures',
                    'Souvenirs',
                    'Stickers',
                    'Wedding Decorations & Gifts',
                ],
                'Toys & Hobbies' => [
                    'Action Figure',
                    'Baby Toys',
                    'Balloons',
                    'Candy Toys',
                    'Classic Toys',
                    'Dolls',
                    'Educational Toys',
                    'Electronic Toys',
                    'Glass Marbles',
                    'Inflatable Toys',
                    'Light-Up Toys',
                    'Noise Maker',
                    'Other Toys & Hobbies',
                    'Outdoor Toys & Structures',
                    'Plastic Toys',
                    'Pretend Play & Preschool',
                    'Solar Toys',
                    'Toy Accessories',
                    'Toy Animal',
                    'Toy Guns',
                    'Toy Parts',
                    'Toy Robots',
                    'Toy Vehicle',
                    'Wind Up Toys',
                    'Wooden Toys',
                ],
            ],
            'Health & Beauty' => [
                'Health & Medical' => [
                    'Animal Extract',
                    'Plant Extracts',
                    'Body Weight',
                    'Health Care Supplement',
                    'Health Care Supplies',
                    'Crude Medicine',
                    'Prepared Drugs In Pieces',
                    'Traditional Patented Medicines',
                    'Body Fluid-Processing & Circulation Devices',
                    'Clinical Analytical Instruments',
                    'Dental Equipment',
                    'Emergency & Clinics Apparatuses',
                    'Equipments of Traditional Chinese Medicine',
                    'General Assay & Diagnostic Apparatuses',
                    'Medical Consumable',
                    'Medical Cryogenic Equipments',
                    'Medical Software',
                    'Physical Therapy Equipments',
                    'Radiology Equipment & Accessories',
                    'Sterilization Equipments',
                    'Surgical Instrument',
                    'Ultrasonic, Optical, Electronic Equipment',
                    'Ward Nursing Equipments',
                    'Medicines',
                ],
                'Beauty & Personal Care' => [
                    'Baby Care',
                    'Bath Supplies',
                    'Beauty Equipment',
                    'Body Art',
                    'Breast Care',
                    'Feminine Hygiene',
                    'Fragrance & Deodorant',
                    'Hair Care',
                    'Hair Extensions & Wigs',
                    'Hair Salon Equipment',
                    'Makeup',
                    'Makeup Tools',
                    'Men Care',
                    'Nail Supplies',
                    'Oral Hygiene',
                    'Other Beauty & Personal Care Products',
                    'Sanitary Paper',
                    'Shaving & Hair Removal',
                    'Skin Care',
                    'Skin Care Tool',
                ],
            ],
            'Home, Lights & Construction' => [
                'Construction & Real Estate' => [
                    'Aluminum Composite Panels',
                    'Balustrades & Handrails',
                    'Bathroom',
                    'Boards',
                    'Building Glass',
                    'Ceilings',
                    'Corner Guards',
                    'Countertops,Vanity Tops & Table Tops',
                    'Curtain Walls & Accessories',
                    'Decorative Films',
                    'Door & Window Accessories',
                    'Doors & Windows',
                    'Earthwork Products',
                    'Elevators & Elevator Parts',
                    'Escalators & Escalator Parts',
                    'Faucets, Mixers & Taps',
                    'Fiberglass Wall Meshes',
                    'Fireplaces,Stoves',
                    'Fireproofing Materials',
                    'Floor Heating Systems & Parts',
                    'Flooring & Accessories',
                    'Formwork',
                    'Gates',
                    'Heat Insulation Materials',
                    'HVAC Systems & Parts',
                    'Kitchen',
                    'Ladders & Scaffoldings',
                    'Landscaping Stone',
                    'Masonry Materials',
                    'Metal Building Materials',
                    'Mosaics',
                    'Mouldings',
                    'Multifunctional Materials',
                    'Other Construction & Real Estate',
                    'Plastic Building Materials',
                    'Quarry Stone & Slabs',
                    'Real Estate',
                    'Soundproofing Materials',
                    'Stairs & Stair Parts',
                    'Stone Carvings and Sculptures',
                    'Sunrooms & Glass Houses',
                    'Tiles & Accessories',
                    'Timber',
                    'Tombstones and Monuments',
                    'Wallpapers/Wall Coating',
                    'Waterproofing Materials',
                ],
                'Home & Garden' => [
                    'Bakeware',
                    'Barware',
                    'Bathroom Products',
                    'Cooking Tools',
                    'Cookware',
                    'Garden Supplies',
                    'Home Decor',
                    'Home Storage & Organization',
                    'Household Chemicals',
                    'Household Cleaning Tools & Accessories',
                    'Household Sundries',
                    'Kitchen Knives & Accessories',
                    'Laundry Products',
                    'Pet Products',
                    'Kitchen,Dining,Bar & Tableware',
                    'Dinnerware',
                    'Drinkware',
                    'Baby Supplies & Products',
                    'Rain Gear',
                    'Lighters & Smoking Accessories',
                ],
                'Lights & Lighting' => [
                    'Emergency Lighting',
                    'Holiday Lighting',
                    'Indoor Lighting',
                    'LED Lighting',
                    'Lighting Accessories',
                    'Lighting Bulbs & Tubes',
                    'Other Lights & Lighting Products',
                    'Outdoor Lighting',
                    'Professional Lighting',
                    'LED Residential Lighting',
                    'LED Outdoor Lighting',
                    'Chandeliers & Pendant Lights',
                    'Ceiling Lights',
                    'Crystal Lights',
                    'Stage Lights',
                    'Street Lights',
                    'Energy Saving & Fluorescent',
                    'LED Landscape Lamps',
                    'LED Professional Lighting',
                    'LED Encapsulation Series',
                ],
                'Furniture' => [
                    'Antique Furniture',
                    'Baby Furniture',
                    'Bamboo Furniture',
                    'Children Furniture',
                    'Commercial Furniture',
                    'Folding Furniture',
                    'Furniture Accessories',
                    'Furniture Hardware',
                    'Furniture Parts',
                    'Glass Furniture',
                    'Home Furniture',
                    'Inflatable Furniture',
                    'Metal Furniture',
                    'Other Furniture',
                    'Outdoor Furniture',
                    'Plastic Furniture',
                    'Rattan / Wicker Furniture',
                    'Wood Furniture',
                    'Living Room Furniture',
                    'Bedroom Furniture',
                ],
            ],
            'Machinery, Industrial Parts & Tools' => [
                'Machinery' => [
                    'Agriculture Machinery & Equipment',
                    'Apparel & Textile Machinery',
                    'Building Material Machinery',
                    'Chemical Machinery & Equipment',
                    'Electronic Products Machinery',
                    'Energy & Mineral Equipment',
                    'Engineering & Construction Machinery',
                    'Food & Beverage Machinery',
                    'General Industrial Equipment',
                    'Home Product Making Machinery',
                    'Industry Laser Equipment',
                    'Machine Tool Equipment',
                    'Metal & Metallurgy Machinery',
                    'Other Machinery & Industry Equipment',
                    'Packaging Machine',
                    'Paper Production Machinery',
                    'Pharmaceutical Machinery',
                    'Plastic & Rubber Machinery',
                    'Printing Machine',
                    'Refrigeration & Heat Exchange Equipment',
                    'Used Machinery & Equipment',
                    'Woodworking Machinery',
                ],
                'Fabrication Services' => [
                    'Custom Fabrication Services',
                    'General Mechanical Components Design Services',
                    'General Mechanical Components Stock',
                    'Industrial Brake',
                    'Machine Tools Accessory',
                    'Moulds',
                    'Other General Mechanical Components',
                    'Other Mechanical Parts',
                    'Used General Mechanical Components',
                    'Coating Services',
                ],
                'Tools & Hardware' => [
                    'Hardware',
                    'Hand Tools',
                    'Material Handling Tools',
                    'Power Tool Accessories',
                    'Power Tools',
                    'Tool Design Services',
                    'Tool Parts',
                    'Tool Processing Services',
                    'Tool Sets',
                    'Tool Stock',
                    'Knife',
                    'Hand Carts & Trolleys',
                    'Lawn Mower',
                    'Sander',
                ],
            ],
            'Metallurgy, Chemicals, Rubber & Plastics' => [
                'Minerals & Metallurgy' => [
                    'Aluminum',
                    'Barbed Wire',
                    'Billets',
                    'Carbon',
                    'Carbon Fiber',
                    'Cast & Forged',
                    'Cemented Carbide',
                    'Ceramic Fiber Products',
                    'Ceramics',
                    'Copper',
                    'Copper Forged',
                    'Fiberglass Products',
                    'Glass',
                    'Graphite Products',
                    'Ingots',
                    'Iron',
                    'Lead',
                    'Lime',
                    'Magnetic Materials',
                    'Metal Scrap',
                    'Metal Slabs',
                    'Mineral Wool',
                    'Molybdenum',
                    'Nickel',
                    'Non-Metallic Mineral Deposit',
                    'Ore',
                    'Other Metals & Metal Products',
                    'Other Non-Metallic Minerals & Products',
                    'Pig Iron',
                    'Quartz Products',
                    'Rare Earth & Products',
                    'Rare Earth Magnets',
                    'Refractory',
                    'Steel',
                    'Titanium',
                    'Tungsten',
                    'Wire Mesh',
                    'Zinc',
                ],
                'Chemicals' => [
                    'Gas Disposal',
                    'Noise Reduction Device',
                    'Other Environmental Products',
                    'Other Excess Inventory',
                    'Recycling',
                    'Sewer',
                    'Waste Management',
                    'Water Treatment',
                    'Textile Waste',
                    'Waste Paper',
                    'Other Recycling Products',
                ],
                'Rubber & Plastics' => [
                    'Plastic Processing Service',
                    'Plastic Products',
                    'Plastic Projects',
                    'Plastic Raw Materials',
                    'Plastic Stocks',
                    'Recycled Plastic',
                    'Recycled Rubber',
                    'Rubber Processing Service',
                    'Rubber Products',
                    'Rubber Projects',
                    'Rubber Raw Materials',
                    'Rubber Stocks',
                    'Plastic Cards',
                    'PVC',
                    'Plastic Tubes',
                    'HDPE',
                    'Rubber Hoses',
                    'Plastic Sheets',
                    'LDPE',
                    'Agricultural Rubber',
                ],
                'Energy' => [
                    'Biodiesel',
                    'Biogas',
                    'Charcoal',
                    'Coal',
                    'Coal Gas',
                    'Coke Fuel',
                    'Crude Oil',
                    'Electricity Generation',
                    'Petrochemical Products',
                    'Solar Energy Products',
                    'Industrial Fuel',
                    'Natural Gas',
                    'Other Energy Related Products',
                    'Wood Pellets',
                    'Solar Energy Systems',
                    'Lubricant',
                    'Diesel Fuel',
                    'Solar Collectors',
                ],
            ],
            'Packaging, Advertising & Office' => [
                'Packaging & Printing' => [
                    'Adhesive Tape',
                    'Agricultural Packaging',
                    'Aluminum Foil',
                    'Apparel Packaging',
                    'Blister Cards',
                    'Bottles',
                    'Cans',
                    'Chemical Packaging',
                    'Composite Packaging Materials',
                    'Cosmetics Packaging',
                    'Electronics Packaging',
                    'Food Packaging',
                    'Gift Packaging',
                    'Handles',
                    'Hot Stamping Foil',
                    'Jars',
                    'Lids, Bottle Caps, Closures',
                    'Media Packaging',
                    'Metallized Film',
                    'Other Packaging Applications',
                    'Other Packaging Materials',
                    'Packaging Bags',
                    'Packaging Boxes',
                    'Packaging Labels',
                    'Packaging Trays',
                    'Packaging Tubes',
                    'Paper & Paperboard',
                    'Paper Packaging',
                    'Pharmaceutical Packaging',
                    'Plastic Film',
                    'Plastic Packaging',
                    'Printing Materials',
                    'Printing Services',
                    'Protective Packaging',
                    'Pulp',
                    'Shrink Film',
                    'Strapping',
                    'Stretch Film',
                    'Tobacco Packaging',
                    'Transport Packaging',
                ],
                'Office & School Supplies' => [
                    'Art Supplies',
                    'Badge Holder & Accessories',
                    'Board',
                    'Board Eraser',
                    'Book Cover',
                    'Books',
                    'Calculator',
                    'Calendar',
                    'Clipboard',
                    'Correction Supplies',
                    'Desk Organizer',
                    'Drafting Supplies',
                    'Easels',
                    'Educational Supplies',
                    'Filing Products',
                    'Letter Pad / Paper',
                    'Magazines',
                    'Map',
                    'Notebooks & Writing Pads',
                    'Office Adhesives & Tapes',
                    'Office Binding Supplies',
                    'Office Cutting Supplies',
                    'Office Equipment',
                    'Office Paper',
                    'Other Office & School Supplies',
                    'Paper Envelopes',
                    'Pencil Cases & Bags',
                    'Pencil Sharpeners',
                    'Printer Supplies',
                    'Stamps',
                    'Stationery Set',
                    'Stencils',
                    'Writing Accessories',
                    'Writing Instruments',
                    'Yellow Pages',
                ],
                'Service Equipment' => [
                    'Advertising Equipment',
                    'Cargo & Storage Equipment',
                    'Commercial Laundry Equipment',
                    'Financial Equipment',
                    'Funeral Supplies',
                    'Other Service Equipment',
                    'Restaurant & Hotel Supplies',
                    'Store & Supermarket Supplies',
                    'Trade Show Equipment',
                    'Vending Machines',
                    'Wedding Supplies',
                    'Display Racks',
                    'Advertising Players',
                    'Advertising Light Boxes',
                    'Hotel Amenities',
                    'POS Systems',
                    'Supermarket Shelves',
                    'Stacking Racks & Shelves',
                    'Refrigeration Equipment',
                    'Trade Show Tent',
                ],
            ],
        ];
    }

    public static function getCategoriesFromDBToSelect(): array
    {
        $ret = [];
        $categories = self::getNotEmptyCategoriesFromDB();
        if (count($categories)) {
            /** @var WP_Term $category */
            foreach ($categories as $category) {
                $ret[$category->term_id] = $category->name;
            }
        }

        return $ret;
    }

    public static function getNotEmptyCategoriesFromDB()
    {
        $orderby = 'name';
        $order = 'asc';
        $hide_empty = true;
        $cat_args = [
            'orderby' => $orderby,
            'order' => $order,
            'hide_empty' => $hide_empty,
        ];

        return get_terms('product_cat', $cat_args);
    }

    public static function getProductCategoryIdsWithParentID(): array
    {
        $ret = [];
        $categories = self::getCategoriesFromDB();
        if (count($categories)) {
            /** @var WP_Term $category */
            foreach ($categories as $category) {
                $ret[$category->term_id] = $category->parent;
            }
        }

        return $ret;
    }

    public static function getCategoriesFromDB()
    {
        $orderby = 'name';
        $order = 'asc';
        $hide_empty = false;
        $cat_args = [
            'orderby' => $orderby,
            'order' => $order,
            'hide_empty' => $hide_empty,
        ];

        return get_terms('product_cat', $cat_args);
    }

    public static function getActiveVendorsForOfferSearch(): array
    {
        $ret = [];
        $vendors = (new VendorRepository())->getActiveVendorsForSelect();

        if (count($vendors)) {
            foreach ($vendors as $vendor) {
                $ret[$vendor['user_id']] = $vendor['store_name'];
            }
        }

        return $ret;
    }

    public static function getLatestCurrenciesForSelect(bool $firstElementUSD = true): array
    {
        $rates = (new CurrencyResource())->toArray((new CurrencyRepository())->getLatestRates());
        $currencies = array_keys($rates['data']);

        if ($firstElementUSD) {
            $tmp = ['USD'];

            foreach ($currencies as $currency) {
                if ($currency == 'USD') {
                    continue;
                }

                $tmp[] = $currency;
            }

            $currencies = $tmp;
            unset($tmp);
        }

        return ArrayHelper::reKeyBySlugFromValue($currencies);
    }

    public static function offerAppearStatusLabel(string $status): string
    {
        $labels = [
            'pending' => 'Pending',
            'active' => 'Accepted',
            'denied' => 'Rejected',
        ];

        return $labels[$status];
    }
}

